import { useEffect, useState } from "react";
import type { StaffRole } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { StaffFormData } from "@/features/staff/data/datasources/staff-api";
import { STAFF_ROLES, staffRoleLabel } from "@/features/staff/domain/entities/staff-management";
import { Field, StaffFormSection, staffInputClass } from "./StaffFormSection";

type Team = { id: string; name: string };

/** The edit form manages current assignments only. Transfer workflows and immutable history live on the detail/history surface. */
export function StaffAssignments({ value, onChange, disabled }: { staffId?: string; value: StaffFormData; onChange: (patch: Partial<StaffFormData>) => void; disabled?: boolean }) {
  const [teams, setTeams] = useState<Team[]>([]);
  useEffect(() => { fetch("/api/teams?approved=true", { credentials: "same-origin" }).then((r) => r.ok ? r.json() : []).then((rows: Team[]) => setTeams(rows)).catch(() => setTeams([])); }, []);
  const assignments = value.assignments ?? [];
  const assignedIds = new Set(assignments.map((assignment) => assignment.teamId));
  const updateAssignment = (index: number, patch: Partial<NonNullable<StaffFormData["assignments"]>[number]>) => onChange({ assignments: assignments.map((assignment, currentIndex) => currentIndex === index ? { ...assignment, ...patch } : assignment) });
  const removeAssignment = (index: number) => onChange({ assignments: assignments.filter((_, currentIndex) => currentIndex !== index) });
  const addAssignment = () => { const nextTeam = teams.find((team) => !assignedIds.has(team.id)); if (assignments.length >= 2 || !nextTeam) return; onChange({ assignments: [...assignments, { teamId: nextTeam.id, role: value.role, effectiveFrom: new Date().toISOString().slice(0, 10) }] }); };
  return <StaffFormSection title="Team assignments" description="A coach may hold up to two assignments at once. Each assignment grants access to that team.">
    <div className="mb-1 flex flex-wrap items-center justify-between gap-3"><span className="font-body text-[11.5px] text-[var(--txm)]">Current access assignments are editable here.</span><Badge variant="outline" className={assignments.length >= 2 ? "border-amber-400/40 bg-amber-400/10 text-amber-400" : "text-[var(--txm)]"}>{assignments.length} / 2 used</Badge></div>
    {teams.length === 0 ? <p className="rounded-xl border border-dashed border-[var(--bord)] px-4 py-6 text-center text-sm text-[var(--txm)]">No eligible teams were returned.</p> : assignments.length === 0 ? <div className="rounded-xl border border-dashed border-[var(--bord)] px-4 py-6 text-center"><div className="font-body text-[13px] font-bold text-[var(--tx)]">No team yet</div><div className="mt-1 font-body text-[11.5px] text-[var(--txm)]">Staff without a team do not appear on club pages or receive team access.</div></div> : <div className="grid gap-3">{assignments.map((assignment, index) => { const team = teams.find((item) => item.id === assignment.teamId); return <div key={`${assignment.teamId}-${index}`} className="rounded-xl border border-[var(--bord)] bg-[var(--surf2)] px-4 py-3.5"><div className="mb-3 flex flex-wrap items-center gap-2.5"><span className="flex h-[22px] w-[22px] shrink-0 items-center justify-center rounded bg-[var(--brand)]/15 font-mono text-[9px] font-bold text-[var(--brandsoft)]">{(team?.name ?? "—").slice(0, 2).toUpperCase()}</span><span className="font-body text-[13.5px] font-bold text-[var(--tx)]">{team?.name ?? "Pick a team"}</span><span className="font-mono text-[11px] text-[var(--txm)]">Staff assignment</span><Button type="button" variant="outline" size="sm" onClick={() => removeAssignment(index)} disabled={disabled} className="ml-auto border-[var(--brand)]/30 bg-[var(--brand)]/10 text-[var(--brand)] hover:bg-[var(--brand)]/15">Remove</Button></div><div className="grid gap-3 min-[561px]:grid-cols-3"><Field label="Team" htmlFor={`assignment-team-${index}`}><Select value={assignment.teamId} onValueChange={(teamId) => updateAssignment(index, { teamId })} disabled={disabled}><SelectTrigger className={staffInputClass} id={`assignment-team-${index}`}><SelectValue placeholder="Pick a team" /></SelectTrigger><SelectContent>{teams.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Capacity" htmlFor={`assignment-role-${index}`}><Select value={assignment.role} onValueChange={(nextRole) => updateAssignment(index, { role: nextRole as StaffRole })} disabled={disabled}><SelectTrigger className={staffInputClass} id={`assignment-role-${index}`}><SelectValue /></SelectTrigger><SelectContent>{STAFF_ROLES.map((item) => <SelectItem key={item} value={item}>{staffRoleLabel(item)}</SelectItem>)}</SelectContent></Select></Field><Field label="Since" htmlFor={`assignment-since-${index}`}><Input className={staffInputClass} id={`assignment-since-${index}`} type="date" value={assignment.effectiveFrom?.slice(0, 10) ?? ""} onChange={(event) => updateAssignment(index, { effectiveFrom: event.target.value || null })} disabled={disabled} /></Field></div></div>; })}</div>}
    <div className="mt-3 flex flex-wrap items-center gap-3"><Button type="button" variant="outline" onClick={addAssignment} disabled={disabled || assignments.length >= 2 || teams.length === assignments.length} className="border-dashed border-[var(--bord)] text-[var(--txd)] hover:border-[var(--brand)] hover:text-[var(--brand)]">+ Add team assignment</Button>{assignments.length >= 2 && <span className="font-body text-[11.5px] text-[var(--txm)]">At the two-team limit. Remove one first to add another.</span>}</div>
  </StaffFormSection>;
}
