import { useEffect, useState } from "react";
import { KeyRound, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StaffFormSection, staffInputClass } from "./StaffFormSection";

type User = { id: string; name: string; email: string; active: boolean };
export function StaffPortalAccess({ staffId, disabled }: { staffId?: string; disabled?: boolean }) {
  const [linked, setLinked] = useState<User | null>(null); const [users, setUsers] = useState<User[]>([]); const [selected, setSelected] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!staffId) return; Promise.all([fetch(`/api/staff/${staffId}/portal`, { credentials: "same-origin" }).then((response) => response.json()), fetch(`/api/staff/${staffId}/portal?available=1`, { credentials: "same-origin" }).then((response) => response.json())]).then(([account, available]) => { setLinked(account.user ?? null); setUsers(available.users ?? []); }).catch(() => setError("Unable to load portal accounts")); }, [staffId]);
  async function update(userId: string | null) { if (!staffId) return; setSaving(true); setError(""); try { const response = await fetch(`/api/staff/${staffId}/portal`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to update portal account"); setLinked(body.user ?? null); setSelected(""); setUsers((current) => current.filter((user) => user.id !== userId)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update portal account"); } finally { setSaving(false); } }
  return <StaffFormSection title="Coach portal access" description="Lets this person sign in and manage their own squad, roster and match sheets.">
    {!staffId ? <p className="font-body text-[11.5px] text-[var(--txm)]">Save the Staff record before connecting a portal account.</p> : <><div className="flex flex-wrap items-center gap-3 rounded-xl border border-[var(--bord)] bg-[var(--surf2)] px-4 py-3.5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[var(--brand)]/10 text-[var(--brand)]"><KeyRound className="h-4 w-4" /></span><div className="min-w-[200px] flex-1"><div className="flex items-center gap-2"><span className="font-body text-[13px] font-bold text-[var(--tx)]">{linked ? linked.name : "No portal account"}</span><Badge variant="outline" className="font-mono text-[9px] uppercase tracking-[0.08em]">{linked ? linked.active ? "Active" : "Inactive" : "None"}</Badge></div><p className="mt-0.5 font-body text-[11.5px] text-[var(--txm)]">{linked ? linked.email : "Connect an existing user account to enable portal access."}</p></div>{linked ? <Button type="button" variant="outline" onClick={() => update(null)} disabled={disabled || saving} className="border-[var(--brand)]/40 bg-[var(--brand)]/10 text-[var(--brand)]">Disconnect</Button> : <div className="flex items-center gap-2"><Select value={selected} onValueChange={setSelected} disabled={disabled || saving}><SelectTrigger className={`${staffInputClass} w-[220px]`}><SelectValue placeholder="Select user" /></SelectTrigger><SelectContent>{users.map((user) => <SelectItem key={user.id} value={user.id}>{user.name} · {user.email}</SelectItem>)}</SelectContent></Select><Button type="button" onClick={() => update(selected)} disabled={!selected || disabled || saving} className="bg-[var(--brand)] font-bold text-white">Connect</Button></div>}</div>{error && <p role="alert" className="mt-2 font-body text-[11px] text-[var(--brand)]">{error}</p>}<div className="mt-4 grid gap-2.5"><div className="font-mono text-[9.5px] uppercase tracking-[0.16em] text-[var(--faint)]">What a coach can do in the portal</div><div className="flex items-start gap-2.5"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span className="font-body text-[12px] text-[var(--txd)]">Portal permissions continue to come from the linked user’s roles and team scope.</span></div></div><div className="mt-4 flex items-center gap-2.5 rounded-lg border border-[var(--bord2)] bg-[var(--surf2)] px-3.5 py-2.5"><ShieldCheck className="h-4 w-4 shrink-0 text-green-500" /><span className="font-body text-[11.5px] text-[var(--txd)]">Two-factor authentication is mandatory for every portal account.</span></div></>}
  </StaffFormSection>;
}
