import { useEffect, useState } from "react";
import { KeyRound, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StaffFormSection, staffInputClass } from "./StaffFormSection";

type User = { id: string; name: string; email: string; active: boolean; activatedAt?: string | null };
export function StaffPortalAccess({ staffId, disabled }: { staffId?: string; disabled?: boolean }) {
  const [linked, setLinked] = useState<User | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!staffId) return; fetch(`/api/staff/${staffId}/portal`, { credentials: "same-origin" }).then((response) => response.json()).then((body) => setLinked(body.user ?? null)).catch(() => setError("Unable to load portal access")); }, [staffId]);
  async function update(action: "invite" | "revoke") { if (!staffId) return; setSaving(true); setError(""); try { const response = await fetch(`/api/staff/${staffId}/portal`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to update portal access"); setLinked(body.user ?? null); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update portal access"); } finally { setSaving(false); } }
  const status = !linked || linked.active === false ? "none" : linked.activatedAt ? "active" : "invited";
  const statusLabel = status === "active" ? "Active" : status === "invited" ? "Invited" : "None";
  const statusText = status === "active" ? "Can sign in and manage their squad, roster and match sheets." : status === "invited" ? "Invitation sent — waiting for them to set a password." : "They cannot sign in or manage their squad yet.";
  return <StaffFormSection title="Coach portal access" description="Lets this person sign in and manage their own squad, roster and match sheets.">
    {!staffId ? <p className="font-body text-[11.5px] text-[var(--txm)]">Save the Staff record before inviting portal access.</p> : <><div className="flex flex-wrap items-center gap-3 rounded-xl border border-[var(--bord)] bg-[var(--surf2)] px-4 py-3.5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[var(--brand)]/10 text-[var(--brand)]"><KeyRound className="h-4 w-4" /></span><div className="min-w-[200px] flex-1"><div className="flex items-center gap-2"><span className="font-body text-[13px] font-bold text-[var(--tx)]">{linked ? linked.name : "No portal account"}</span><Badge variant="outline" className="font-mono text-[9px] uppercase tracking-[0.08em]">{statusLabel}</Badge></div><p className="mt-0.5 font-body text-[11.5px] text-[var(--txm)]">{linked ? linked.email : statusText}</p><p className="mt-1 font-body text-[11.5px] text-[var(--txd)]">{linked ? statusText : "Invite creates the secure account from this Staff record."}</p></div>{status === "active" ? <Button type="button" variant="outline" onClick={() => update("revoke")} disabled={disabled || saving} className="border-[var(--brand)]/40 bg-[var(--brand)]/10 text-[var(--brand)]">Revoke access</Button> : <Button type="button" onClick={() => update("invite")} disabled={disabled || saving} className="bg-[var(--brand)] font-bold text-white">{status === "invited" ? "Resend invite" : "Invite to portal"}</Button>}</div>{error && <p role="alert" className="mt-2 font-body text-[11px] text-[var(--brand)]">{error}</p>}<div className="mt-4 grid gap-2.5"><div className="font-mono text-[9.5px] uppercase tracking-[0.16em] text-[var(--faint)]">What a coach can do in the portal</div><div className="flex items-start gap-2.5"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-green-500" /><span className="font-body text-[12px] text-[var(--txd)]">Portal permissions continue to come from the linked user’s Coach role and current team assignments.</span></div></div><div className="mt-4 flex items-center gap-2.5 rounded-lg border border-[var(--bord2)] bg-[var(--surf2)] px-3.5 py-2.5"><ShieldCheck className="h-4 w-4 shrink-0 text-green-500" /><span className="font-body text-[11.5px] text-[var(--txd)]">Two-factor authentication is mandatory for every portal account.</span></div></>}
  </StaffFormSection>;
}
