import { useEffect, useState } from "react";
import { Check, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { StaffFormData } from "@/features/staff/data/datasources/staff-api";
import { staffRoleLabel } from "@/features/staff/domain/entities/staff-management";

export function StaffFormAside({ value, staffId, onDelete }: { value: StaffFormData; staffId?: string; onDelete?: () => void }) {
  const [teams, setTeams] = useState<Array<{ id: string; name: string }>>([]);
  useEffect(() => { fetch("/api/teams?approved=true", { credentials: "same-origin" }).then((response) => response.ok ? response.json() : []).then((rows) => setTeams(rows)).catch(() => setTeams([])); }, []);
  const name = `${value.firstName} ${value.lastName}`.trim() || "Unnamed staff member";
  const initials = `${value.firstName[0] ?? ""}${value.lastName[0] ?? ""}`.toUpperCase() || "?";
  const assignments = value.assignments ?? [];
  const checks = [{ label: "First and last name", ok: Boolean(value.firstName.trim() && value.lastName.trim()), bad: "First and last name required" }, { label: "Role selected", ok: Boolean(value.role), bad: "Select a role" }, { label: "Public profile image", ok: Boolean(value.image), bad: "Add a public profile image" }, { label: "At least one team", ok: Boolean(assignments.length), bad: "No team assigned" }];
  const teamName = (id: string) => teams.find((team) => team.id === id)?.name ?? id;
  const shortName = (id: string) => teamName(id).slice(0, 3).toUpperCase();
  const dateLabel = (date?: string) => date ? new Intl.DateTimeFormat(undefined, { day: "2-digit", month: "short", year: "numeric" }).format(new Date(date)) : "—";
  const recordLabel = (date: string | undefined, actor: string | null | undefined) => `${dateLabel(date)} · ${actor || "unknown editor"}`;
  return <aside className="sticky top-4 grid gap-4 self-start max-[1080px]:static">
    <section className="overflow-hidden rounded-2xl border border-[var(--bord)] bg-[var(--surf)]"><div className="border-b border-[var(--bord2)] px-4 py-3"><div className="font-mono text-[9.5px] uppercase tracking-[0.16em] text-[var(--faint)]">Preview</div><div className="mt-0.5 font-body text-[11.5px] text-[var(--txm)]">How this row reads in the staff list</div></div><div className="px-4 py-4"><div className="flex items-center gap-3"><span className="flex h-[34px] w-[34px] shrink-0 items-center justify-center overflow-hidden rounded-full border border-[var(--bord2)] bg-[var(--surf2)] font-mono text-[11.5px] font-bold text-[var(--txd)]">{value.image ? <img src={value.image} alt="" className="h-full w-full object-cover" /> : initials}</span><div className="min-w-0 flex-1"><div className="truncate font-body text-[13.5px] font-bold text-[var(--tx)]">{name}</div><div className="mt-[3px] truncate font-mono text-[10.5px] text-[var(--txm)]">{assignments.length ? assignments.map((assignment) => teamName(assignment.teamId)).join(" · ") : "No team assigned"}</div></div><Badge className="bg-[var(--brand)]/15 text-[var(--brandsoft)] hover:bg-[var(--brand)]/15">{staffRoleLabel(value.role)}</Badge></div><div className="mt-3 flex flex-wrap gap-1.5">{assignments.length ? assignments.map((assignment) => <span key={assignment.teamId} className="inline-flex items-center gap-1.5 rounded-md border border-[var(--bord)] bg-[var(--surf2)] px-2 py-1 font-body text-[11px] font-semibold text-[var(--txd)]"><span className="flex h-[14px] w-[14px] items-center justify-center rounded-[3px] bg-[var(--brand)]/15 font-mono text-[8px] font-bold text-[var(--brandsoft)]">{shortName(assignment.teamId)}</span>{teamName(assignment.teamId)}</span>) : <span className="inline-flex items-center gap-1.5 rounded-md border border-dashed border-[var(--bord)] px-2 py-1 font-body text-[11px] font-semibold text-[var(--faint)]"><span className="h-1.5 w-1.5 rounded-full bg-amber-400" />No team</span>}</div></div></section>
    <section className="overflow-hidden rounded-2xl border border-[var(--bord)] bg-[var(--surf)]"><div className="border-b border-[var(--bord2)] px-4 py-3"><div className="font-mono text-[9.5px] uppercase tracking-[0.16em] text-[var(--faint)]">Before saving</div></div><div className="grid gap-2.5 px-4 py-4">{checks.map((check) => <div key={check.label} className="flex items-start gap-2.5"><span className={`mt-[2px] flex h-4 w-4 shrink-0 items-center justify-center rounded font-mono text-[9px] font-bold ${check.ok ? "bg-green-500/15 text-green-400" : "bg-amber-400/15 text-amber-400"}`}>{check.ok ? <Check className="h-3 w-3" /> : "!"}</span><span className={`font-body text-[11.5px] ${check.ok ? "text-[var(--txd)]" : "text-[var(--tx)]"}`}>{check.ok ? check.label : check.bad}</span></div>)}</div></section>
    {staffId && <><section className="overflow-hidden rounded-2xl border border-[var(--bord)] bg-[var(--surf)]"><div className="border-b border-[var(--bord2)] px-4 py-3"><div className="font-mono text-[9.5px] uppercase tracking-[0.16em] text-[var(--faint)]">Record</div></div><div className="grid gap-2 px-4 py-4"><div className="flex items-center justify-between gap-3"><span className="font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--faint)]">Created</span><span className="truncate font-body text-[11.5px] font-semibold text-[var(--txd)]">{recordLabel(value.createdAt, "import")}</span></div><div className="flex items-center justify-between gap-3"><span className="font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--faint)]">Last edited</span><span className="truncate font-body text-[11.5px] font-semibold text-[var(--txd)]">{recordLabel(value.updatedAt, value.lastEditedBy)}</span></div><div className="flex items-center justify-between gap-3"><span className="font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--faint)]">Teams</span><span className="truncate font-body text-[11.5px] font-semibold text-[var(--txd)]">{assignments.length}</span></div><div className="flex items-center justify-between gap-3"><span className="font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--faint)]">Staff ID</span><span className="truncate font-body text-[11.5px] font-semibold text-[var(--txd)]">{value.id || "—"}</span></div><a href="/admin/audit-logs" className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--brand)] no-underline hover:underline">Full history →</a></div></section><section className="overflow-hidden rounded-2xl border border-[var(--brand)]/30 bg-[var(--brand)]/[0.06]"><div className="border-b border-[var(--brand)]/20 px-4 py-3"><div className="font-mono text-[9.5px] uppercase tracking-[0.16em] text-[var(--brandsoft)]">Danger zone</div></div><div className="grid gap-2.5 px-4 py-4"><Button type="button" onClick={onDelete} className="w-full border border-[var(--brand)]/40 bg-[var(--brand)]/[0.12] text-[var(--brand)] hover:bg-[var(--brand)]/[0.2]"><Trash2 className="mr-2 h-3.5 w-3.5" />Delete permanently…</Button><span className="font-body text-[11px] text-[var(--txm)]">Deleting is refused while this person appears on a match sheet. Deactivate instead to preserve the record.</span></div></section></>}
  </aside>;
}
