import { useEffect, useMemo, useState } from "react";
import type { StaffRole } from "@prisma/client";
import { ArrowRight, History, Loader2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { StaffFormData } from "@/features/staff/data/datasources/staff-api";
import { staffHistoryApi, type StaffAssignmentHistoryRecord, type StaffTransferRecord } from "@/features/staff/data/datasources/staff-history-api";
import { STAFF_ROLES, staffRoleLabel } from "@/features/staff/domain/entities/staff-management";
import { Field, StaffFormSection, staffInputClass } from "./StaffFormSection";

type Team = { id: string; name: string };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "Open-ended";

export function StaffAssignments({ staffId, value, onChange, disabled }: { staffId?: string; value: StaffFormData; onChange: (patch: Partial<StaffFormData>) => void; disabled?: boolean }) {
  const [teams, setTeams] = useState<Team[]>([]); const [history, setHistory] = useState<StaffAssignmentHistoryRecord[]>([]); const [transfers, setTransfers] = useState<StaffTransferRecord[]>([]); const [error, setError] = useState(""); const [transferring, setTransferring] = useState(false);
  const [fromId, setFromId] = useState(""); const [toTeamId, setToTeamId] = useState(""); const [role, setRole] = useState<StaffRole>(value.role); const [effectiveFrom, setEffectiveFrom] = useState(new Date().toISOString().slice(0, 10)); const [reason, setReason] = useState("");
  const loadHistory = () => { if (!staffId) return; Promise.all([staffHistoryApi.list(staffId), staffHistoryApi.transfers(staffId)]).then(([assignments, events]) => { setHistory(assignments); setTransfers(events); }).catch((e) => setError(e instanceof Error ? e.message : "Unable to load transfer history")); };
  useEffect(() => { fetch("/api/teams?approved=true", { credentials: "same-origin" }).then((r) => r.ok ? r.json() : []).then((rows: Team[]) => setTeams(rows)).catch(() => setTeams([])); loadHistory(); }, [staffId]);
  const current = useMemo(() => history.filter((item) => !item.effectiveTo), [history]);
  const assignedIds = new Set(value.assignments?.map((assignment) => assignment.teamId) ?? []);
  async function transfer() { if (!staffId || !fromId || !toTeamId || !effectiveFrom) return; setTransferring(true); setError(""); try { await staffHistoryApi.transfer(staffId, { fromTeamStaffId: fromId, toTeamId, role, effectiveFrom, transferReason: reason.trim() || undefined }); onChange({ assignments: [...(value.assignments ?? []).filter((assignment) => assignment.teamId !== history.find((item) => item.id === fromId)?.teamId), { teamId: toTeamId, role, effectiveFrom }] }); setFromId(""); setToTeamId(""); setReason(""); loadHistory(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to transfer staff member"); } finally { setTransferring(false); } }
  const availableTeams = teams.filter((team) => team.id !== history.find((item) => item.id === fromId)?.teamId && !current.some((item) => item.teamId === team.id));
  const assignments = value.assignments ?? [];
  const updateAssignment = (index: number, patch: Partial<NonNullable<StaffFormData["assignments"]>[number]>) => onChange({ assignments: assignments.map((assignment, currentIndex) => currentIndex === index ? { ...assignment, ...patch } : assignment) });
  const removeAssignment = (index: number) => onChange({ assignments: assignments.filter((_, currentIndex) => currentIndex !== index) });
  const addAssignment = () => { const nextTeam = teams.find((team) => !assignedIds.has(team.id)); if (assignments.length >= 2 || !nextTeam) return; onChange({ assignments: [...assignments, { teamId: nextTeam.id, role: value.role, effectiveFrom: new Date().toISOString().slice(0, 10) }] }); };
  return <div className="space-y-5">
    <StaffFormSection title="Team assignments" description="A coach may hold up to two assignments at once. Each assignment grants access to that team.">
      <div className="mb-1 flex flex-wrap items-center justify-between gap-3"><span className="font-body text-[11.5px] text-[var(--txm)]">Current access assignments are editable here.</span><Badge variant="outline" className={assignments.length >= 2 ? "border-amber-400/40 bg-amber-400/10 text-amber-400" : "text-[var(--txm)]"}>{assignments.length} / 2 used</Badge></div>
      {teams.length === 0 ? <p className="rounded-xl border border-dashed border-[var(--bord)] px-4 py-6 text-center text-sm text-[var(--txm)]">No eligible teams were returned.</p> : assignments.length === 0 ? <div className="rounded-xl border border-dashed border-[var(--bord)] px-4 py-6 text-center"><div className="font-body text-[13px] font-bold text-[var(--tx)]">No team yet</div><div className="mt-1 font-body text-[11.5px] text-[var(--txm)]">Staff without a team do not appear on club pages or receive team access.</div></div> : <div className="grid gap-3">{assignments.map((assignment, index) => { const team = teams.find((item) => item.id === assignment.teamId); return <div key={`${assignment.teamId}-${index}`} className="rounded-xl border border-[var(--bord)] bg-[var(--surf2)] px-4 py-3.5"><div className="mb-3 flex flex-wrap items-center gap-2.5"><span className="flex h-[22px] w-[22px] shrink-0 items-center justify-center rounded bg-[var(--brand)]/15 font-mono text-[9px] font-bold text-[var(--brandsoft)]">{(team?.name ?? "—").slice(0, 2).toUpperCase()}</span><span className="font-body text-[13.5px] font-bold text-[var(--tx)]">{team?.name ?? "Pick a team"}</span><span className="font-mono text-[11px] text-[var(--txm)]">Staff assignment</span><Button type="button" variant="outline" size="sm" onClick={() => removeAssignment(index)} disabled={disabled} className="ml-auto border-[var(--brand)]/30 bg-[var(--brand)]/10 text-[var(--brand)] hover:bg-[var(--brand)]/15">Remove</Button></div><div className="grid gap-3 min-[561px]:grid-cols-3"><Field label="Team" htmlFor={`assignment-team-${index}`}><Select value={assignment.teamId} onValueChange={(teamId) => updateAssignment(index, { teamId })} disabled={disabled}><SelectTrigger className={staffInputClass} id={`assignment-team-${index}`}><SelectValue placeholder="Pick a team" /></SelectTrigger><SelectContent>{teams.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Capacity" htmlFor={`assignment-role-${index}`}><Select value={assignment.role} onValueChange={(nextRole) => updateAssignment(index, { role: nextRole as StaffRole })} disabled={disabled}><SelectTrigger className={staffInputClass} id={`assignment-role-${index}`}><SelectValue /></SelectTrigger><SelectContent>{STAFF_ROLES.map((item) => <SelectItem key={item} value={item}>{staffRoleLabel(item)}</SelectItem>)}</SelectContent></Select></Field><Field label="Since" htmlFor={`assignment-since-${index}`}><Input className={staffInputClass} id={`assignment-since-${index}`} type="date" value={assignment.effectiveFrom?.slice(0, 10) ?? ""} onChange={(event) => updateAssignment(index, { effectiveFrom: event.target.value || null })} disabled={disabled} /></Field></div></div>; })}</div>}
      <div className="mt-3 flex flex-wrap items-center gap-3"><Button type="button" variant="outline" onClick={addAssignment} disabled={disabled || assignments.length >= 2 || teams.length === assignments.length} className="border-dashed border-[var(--bord)] text-[var(--txd)] hover:border-[var(--brand)] hover:text-[var(--brand)]">+ Add team assignment</Button>{assignments.length >= 2 && <span className="font-body text-[11.5px] text-[var(--txm)]">At the two-team limit. Remove one first to add another.</span>}</div>
    </StaffFormSection>
    {staffId && <StaffFormSection title="Transfer to another team" description="This ends the current assignment, creates the new assignment, and records an immutable transfer event.">
      {error && <p role="alert" className="mb-4 rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      {current.length === 0 ? <p className="text-sm text-[#8a817a]">A current assignment is required before a transfer can be recorded.</p> : <div className="grid gap-4 md:grid-cols-2"><Field label="Transfer from" htmlFor="transfer-from"><Select value={fromId} onValueChange={setFromId} disabled={transferring}><SelectTrigger className={staffInputClass} id="transfer-from"><SelectValue placeholder="Select current assignment" /></SelectTrigger><SelectContent>{current.map((item) => <SelectItem key={item.id} value={item.id}>{item.team.name} · {staffRoleLabel(item.role)}</SelectItem>)}</SelectContent></Select></Field><Field label="Transfer to" htmlFor="transfer-to"><Select value={toTeamId} onValueChange={setToTeamId} disabled={transferring}><SelectTrigger className={staffInputClass} id="transfer-to"><SelectValue placeholder="Select new team" /></SelectTrigger><SelectContent>{availableTeams.map((team) => <SelectItem key={team.id} value={team.id}>{team.name}</SelectItem>)}</SelectContent></Select></Field><Field label="New role" htmlFor="transfer-role"><Select value={role} onValueChange={(next) => setRole(next as StaffRole)} disabled={transferring}><SelectTrigger className={staffInputClass} id="transfer-role"><SelectValue /></SelectTrigger><SelectContent>{STAFF_ROLES.map((item) => <SelectItem key={item} value={item}>{staffRoleLabel(item)}</SelectItem>)}</SelectContent></Select></Field><Field label="Effective date" htmlFor="transfer-effective"><Input className={staffInputClass} id="transfer-effective" type="date" value={effectiveFrom} onChange={(e) => setEffectiveFrom(e.target.value)} disabled={transferring} /></Field><div className="md:col-span-2"><Field label="Reason (optional)" htmlFor="transfer-reason"><Textarea className={staffInputClass} id="transfer-reason" rows={3} maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} disabled={transferring} placeholder="Why is this assignment changing?" /></Field></div><div className="md:col-span-2"><Button type="button" onClick={transfer} disabled={transferring || !fromId || !toTeamId}>{transferring ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ArrowRight className="mr-2 h-4 w-4" />}Record transfer</Button></div></div>}
    </StaffFormSection>}
    {staffId && <StaffFormSection title="Transfer history" description="Immutable transfer events recorded from the durable Staff assignment timeline.">{transfers.length === 0 ? <p className="text-sm text-[#8a817a]">No transfer events recorded yet. Older assignments may predate transfer history.</p> : <div className="space-y-3">{transfers.map((item) => <div key={item.id} className="flex flex-wrap items-start justify-between gap-3 rounded-xl border border-white/[0.08] bg-white/[0.03] p-4"><div><div className="flex items-center gap-2 text-sm font-semibold"><span>{item.fromTeam.name}</span><ArrowRight className="h-4 w-4 text-[#e4002b]" /><span>{item.toTeam.name}</span></div><p className="mt-1 text-xs text-[#8a817a]">Effective {dateLabel(item.effectiveFrom)} · recorded {dateLabel(item.createdAt)}</p>{item.reason && <p className="mt-2 text-sm text-[#b8afa6]">{item.reason}</p>}</div><Badge variant="outline"><History className="mr-1 h-3 w-3" />Transfer</Badge></div>)}</div>}</StaffFormSection>}
  </div>;
}
