import { useEffect, useState, type FormEvent } from "react";
import { navigate } from "astro:transitions/client";
import { AlertTriangle, CheckCircle, Loader2 } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import type { StaffRole } from "@prisma/client";
import { staffApi, type StaffFormData } from "@/features/staff/data/datasources/staff-api";
import { StaffAssignments } from "./StaffAssignments";
import { StaffComplianceFields } from "./StaffComplianceFields";
import { StaffFormAside } from "./StaffFormAside";
import { StaffProfileFields } from "./StaffProfileFields";

const EMPTY: StaffFormData = { firstName: "", lastName: "", slug: "", role: "COACH", active: true, assignments: [] };
const isoDate = (value: Date | string | null | undefined) => value ? new Date(value).toISOString() : undefined;
const toForm = (staff: Awaited<ReturnType<typeof staffApi.get>>): StaffFormData => ({
  id: staff.id, createdAt: isoDate(staff.createdAt), updatedAt: isoDate(staff.updatedAt), lastEditedBy: (staff as typeof staff & { lastEditedBy?: string | null }).lastEditedBy, firstName: staff.firstName, lastName: staff.lastName, slug: staff.slug, tagline: staff.tagline ?? "", email: staff.email ?? "", phone: staff.phone ?? "", phoneSecondary: staff.phoneSecondary ?? "", nextOfKin: staff.nextOfKin ?? "", role: staff.role,
  bio: staff.bio ?? "", internalNote: staff.internalNote ?? "", image: staff.image ?? "", licenseNumber: staff.licenseNumber ?? "", licenseExpiresAt: staff.licenseExpiresAt?.toISOString() ?? null, safeguardingStatus: staff.safeguardingStatus ?? "", idNumber: staff.idNumber ?? "", active: staff.active, approved: staff.approved,
  assignments: staff.teams.filter((assignment) => assignment.effectiveFrom <= new Date() && (!assignment.effectiveTo || assignment.effectiveTo > new Date())).map((assignment) => ({ teamId: assignment.teamId, role: assignment.role as StaffRole, effectiveFrom: assignment.effectiveFrom?.toISOString() ?? null })),
});

export default function StaffEditor({ staffId }: { staffId?: string }) {
  const [form, setForm] = useState<StaffFormData>(EMPTY); const [initialForm, setInitialForm] = useState<StaffFormData>(EMPTY); const [loading, setLoading] = useState(Boolean(staffId)); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [saveAnother, setSaveAnother] = useState(false);
  useEffect(() => { if (!staffId) return; staffApi.get(staffId).then((staff) => { const next = toForm(staff); setForm(next); setInitialForm(next); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [staffId]);
  const update = (patch: Partial<StaffFormData>) => setForm((current) => ({ ...current, ...patch }));
  const dirty = JSON.stringify(form) !== JSON.stringify(initialForm);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setSaved(false); try { if (staffId) await staffApi.update(staffId, form); else await staffApi.create(form); if (!staffId && saveAnother) { setForm(EMPTY); setInitialForm(EMPTY); setSaveAnother(false); setSaved(true); } else { setInitialForm(form); setSaved(true); window.setTimeout(() => navigate("/admin/staff"), 700); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to save staff member"); } finally { setSaving(false); } }
  async function deleteStaff() { if (!staffId || !window.confirm("Delete this staff member permanently? This cannot be undone.")) return; setSaving(true); setError(""); try { await staffApi.remove(staffId); await navigate("/admin/staff"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete staff member"); } finally { setSaving(false); } }
  if (loading) return <div className="mx-auto max-w-[1240px] space-y-4"><Skeleton className="h-8 w-48" /><Skeleton className="h-20 w-full" /><Skeleton className="h-96 w-full" /></div>;
  const isCreate = !staffId; const pageTitle = isCreate ? "Create staff member" : "Edit staff member";
  return <div className="relative min-h-full bg-[var(--bg)] px-4 pb-8 pt-5 font-body text-[var(--tx)] sm:px-6 sm:pt-6">
    <div className="mx-auto max-w-[1240px]"><div className="mb-4 flex flex-wrap items-center gap-2 font-mono text-[11px] text-[var(--txm)]"><a href="/admin/staff" className="no-underline hover:text-[var(--brand)]">Staff</a><span className="text-[var(--faint)]">/</span>{staffId && <><a href={`/admin/staff/${staffId}`} className="no-underline hover:text-[var(--brand)]">{form.firstName} {form.lastName}</a><span className="text-[var(--faint)]">/</span></>}<span className="text-[var(--txd)]">{pageTitle}</span></div>
      <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div className="min-w-[320px] flex-1"><div className="mb-1.5 font-mono text-[10.5px] uppercase tracking-[0.18em] text-[var(--brand)]">Personnel · Staff</div><h1 className="font-display text-[32px] uppercase leading-none text-[var(--tx)]">{pageTitle}</h1><p className="mt-2 max-w-[640px] font-body text-[13px] text-[var(--txm)]">{isCreate ? "Create a complete staff record for the public directory and internal operations." : "Update the staff record, assignments, and operational details without losing its history."}</p></div><div className="flex items-center gap-2">{staffId && form.slug && <a href={`/staff/${form.slug}`} className="rounded-lg border border-[var(--bord)] bg-[var(--surf)] px-3.5 py-2.5 text-[12px] font-bold text-[var(--txd)] no-underline hover:border-[var(--brand)] hover:text-[var(--brand)]">View public profile</a>}<a href="/admin/staff" className="rounded-lg border border-[var(--bord)] bg-[var(--surf)] px-3.5 py-2.5 text-[12px] font-bold text-[var(--txd)] no-underline hover:border-[var(--brand)] hover:text-[var(--brand)]">Cancel</a></div></div>
      {error && <Alert variant="destructive" className="mb-4 border-[var(--brand)]/40 bg-[var(--brand)]/10 text-[var(--brand)]"><AlertTriangle className="h-4 w-4" /><AlertDescription>{error}</AlertDescription></Alert>}{saved && <Alert className="mb-4 border-green-500/40 bg-green-500/10 text-green-300"><CheckCircle className="h-4 w-4" /><AlertDescription>Staff member saved. Returning to the directory…</AlertDescription></Alert>}
      <form onSubmit={submit}><div className="grid items-start gap-5 min-[1081px]:grid-cols-[minmax(0,1fr)_336px]"><div className="grid gap-4"><StaffProfileFields value={form} onChange={update} disabled={saving} /><StaffAssignments staffId={staffId} value={form} onChange={update} disabled={saving} /><StaffComplianceFields staffId={staffId} value={form} onChange={update} disabled={saving} /></div><StaffFormAside value={form} staffId={staffId} onDelete={deleteStaff} /></div>
        <div className="pointer-events-none sticky bottom-0 z-20 flex justify-center px-4 pb-5 pt-4"><div className="pointer-events-auto flex w-fit max-w-full flex-wrap items-center gap-4 rounded-xl border border-[var(--bord)] bg-[var(--surf)] px-4 py-3 shadow-[0_18px_50px_rgba(0,0,0,0.45)]"><div className="flex items-center gap-2"><span className={`h-[7px] w-[7px] rounded-full ${dirty ? "bg-amber-400" : "bg-green-400"}`} /><span className="text-[12.5px] font-semibold text-[var(--tx)]">{dirty ? (form.firstName.trim() && form.lastName.trim() ? "Ready to save" : "Name is required") : "All changes saved"}</span><span className="hidden font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--faint)] min-[701px]:inline">{dirty ? "Changes are validated server-side" : "No unsaved changes"}</span></div><div className="flex items-center gap-2"><Button type="button" variant="ghost" onClick={() => setForm(initialForm)} disabled={saving || !dirty} className="text-[var(--txd)] hover:bg-[var(--hov)] hover:text-[var(--tx)]">Revert</Button>{isCreate && <Button type="submit" variant="outline" onClick={() => setSaveAnother(true)} disabled={saving || !dirty || !form.firstName.trim() || !form.lastName.trim()} className="border-[var(--bord)] bg-[var(--surf2)] text-[var(--txd)]">Save &amp; add another</Button>}<Button type="submit" disabled={saving || !dirty || !form.firstName.trim() || !form.lastName.trim()} className="bg-[var(--brand)] font-bold text-white hover:opacity-90">{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}{isCreate ? "Create staff member" : "Save changes"}</Button></div></div></div>
      </form>
    </div>
  </div>;
}
