import type { MouseEvent } from 'react';
import { ArrowDown, ArrowUp, Check, CheckCircle2, Download, LogOut, MoreHorizontal, RotateCcw, Search, Trash2, Upload, UserRound, UsersRound, X } from 'lucide-react';
import { PLAYER_POSITIONS, getInitials, getMissingProfileFields, getPlayerName, getPositionKey, getProfileCompleteness } from '../../domain/entities/player-directory';
import { usePlayersDirectory } from './hooks/usePlayersDirectory';
import ActionDialog from '../../../cms/presentation/v2/ActionDialog';
import RowMenu from '../../../cms/presentation/v2/RowMenu';
import TransferDialog from './TransferDialog';

export default function PlayersPageV2() {
  const directory = usePlayersDirectory();
  if (directory.loading) return <div className="eb-players-loading"><div /><div /><div /></div>;
  if (directory.error) return <div className="eb-players-error"><strong>Unable to load players</strong><span>{directory.error}</span><button onClick={directory.load}>Try again</button></div>;
  const letters = ['All', ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')];
  const presentLetters = new Set(directory.base.map((player) => getPlayerName(player)[0]?.toUpperCase()));
  const incomplete = directory.base.filter((player) => getMissingProfileFields(player).length > 0).length;
  const approved = directory.base.filter((player) => player.approved).length;
  const pending = directory.base.length - approved;
  const filtered = directory.filters;
  const hasFilters = filtered.search || filtered.team !== 'All teams' || filtered.position !== 'All' || filtered.status !== 'All' || filtered.letter !== 'All' || filtered.participation !== 'all';

  return <div className="eb-players-page">
    <header className="eb-players-heading"><div><div className="eb-players-eyebrow">Personnel</div><h1>Players</h1><p>Player profiles across the league. Scope the list to a competition edition to see who is registered, or switch to the full directory to manage every profile on record.</p></div><div className="eb-players-actions"><button><Upload size={14} /> Import CSV</button><button onClick={() => directory.exportCsv(directory.filtered.map((player) => player.id))} title="Download the players currently shown as CSV"><Download size={14} /> Export</button><a href="/admin/players/new">＋ New Player</a></div></header>
    <ScopeBar {...directory} />
    {directory.scope === 'season' && <div className="eb-players-kpis"><Kpi value={directory.base.length} label="Registered Players" color="var(--brand)" /><Kpi value={approved} label="Approved" color="#1f8a5b" /><Kpi value={pending} label="Awaiting Review" color="#d98324" action={pending ? 'Review pending' : undefined} onAction={() => directory.updateFilter('status', 'pending')} /><Kpi value={incomplete} label="Incomplete Profiles" color="#2a6fdb" action={incomplete ? 'Show incomplete' : undefined} onAction={() => directory.updateFilter('status', 'incomplete')} /></div>}
    <section className="eb-players-card"><div className="eb-players-toolbar"><label><Search size={15} /><input value={filtered.search} onChange={(event) => directory.updateFilter('search', event.target.value)} placeholder="Name, team or jersey…" /></label><select value={filtered.team} onChange={(event) => directory.updateFilter('team', event.target.value)}>{directory.teamOptions.map((team) => <option key={team}>{team}</option>)}</select><select value={filtered.status} onChange={(event) => directory.updateFilter('status', event.target.value)}><option value="All">All status</option><option value="approved">Approved</option><option value="pending">Pending</option><option value="incomplete">Incomplete profile</option></select><div className="eb-segment eb-participation" role="group" aria-label="League participation">{([['all', 'All'], ['active', 'Active'], ['dropped', 'Dropped out']] as const).map(([value, label]) => <button key={value} className={filtered.participation === value ? 'active' : ''} onClick={() => directory.updateFilter('participation', value)}>{label}{value === 'dropped' && <b>{directory.droppedCount}</b>}</button>)}</div><div className="eb-position-pills">{['All', ...Object.keys(PLAYER_POSITIONS)].map((position) => <button key={position} className={filtered.position === position ? 'active' : ''} onClick={() => directory.updateFilter('position', position)}>{position === 'All' ? 'ALL' : position}</button>)}</div>{hasFilters && <button className="eb-reset" onClick={directory.resetFilters}>Reset</button>}</div>
      <div className="eb-players-letters">{letters.map((value) => <button key={value} disabled={value !== 'All' && !presentLetters.has(value)} className={filtered.letter === value ? 'active' : ''} onClick={() => (value === 'All' || presentLetters.has(value)) && directory.updateFilter('letter', value)}>{value}</button>)}</div>
      {directory.notice && <div className={`eb-players-notice ${directory.notice.tone}`} role="status"><span>{directory.notice.text}</span><button aria-label="Dismiss" onClick={() => directory.setNotice(null)}><X size={14} /></button></div>}
      {directory.selected.size > 0 && <BulkBar {...directory} />}
      <PlayerTable {...directory} />
      <footer className="eb-players-footer"><span>Showing {directory.filtered.length ? `${(directory.page - 1) * 10 + 1}–${Math.min(directory.page * 10, directory.filtered.length)}` : '0'} of {directory.filtered.length} players</span><div><button disabled={directory.page === 1} onClick={() => directory.setPage(Math.max(1, directory.page - 1))}>Prev</button>{Array.from({ length: directory.pageCount }, (_, index) => index + 1).slice(0, 7).map((number) => <button key={number} className={number === directory.page ? 'active' : ''} onClick={() => directory.setPage(number)}>{number}</button>)}<button disabled={directory.page === directory.pageCount} onClick={() => directory.setPage(Math.min(directory.pageCount, directory.page + 1))}>Next</button></div></footer>
    </section>
    {directory.dialog && <PlayersDialog {...directory} />}
  </div>;
}

function ScopeBar(directory: ReturnType<typeof usePlayersDirectory>) { return <section className="eb-players-scope"><span className="eb-players-label">Scope</span><div className="eb-segment"><button className={directory.scope === 'season' ? 'active' : ''} onClick={() => directory.setScope('season')}>Competition edition</button><button className={directory.scope === 'directory' ? 'active' : ''} onClick={() => directory.setScope('directory')}>Full directory</button></div>{directory.scope === 'season' && <><span className="eb-scope-divider">›</span><select value={directory.seasonId} onChange={(event) => { directory.setSeasonId(event.target.value); directory.setLeagueSeasonId(''); }}><option value="">Select season…</option>{directory.seasons.map((season) => <option key={season.id} value={season.id}>{season.name}</option>)}</select><div className="eb-segment league">{directory.editions.map((edition: any) => <button key={edition.id} className={directory.leagueSeasonId === edition.id ? 'active' : ''} onClick={() => directory.setLeagueSeasonId(edition.id)}>{edition.league?.name ?? 'League'}</button>)}</div></>}<div className="eb-scope-meta"><b className={directory.scope === 'season' ? 'live' : ''}>● {directory.scope === 'season' ? directory.currentSeason?.status ?? 'Select a season' : 'All editions'}</b><span>{directory.scope === 'season' && directory.seasonId ? `${directory.currentSeason?.name ?? ''} · ${directory.base.length} registered` : directory.scope === 'season' ? 'Choose a season to filter the directory' : 'Profiles are shared across every edition'}</span></div></section>; }

function PlayerTable(directory: ReturnType<typeof usePlayersDirectory>) { return directory.visible.length === 0 ? <div className="eb-players-empty"><UserRound size={25} />{directory.filters.participation === 'dropped' && !directory.droppedCount ? <><strong>No dropped-out players</strong><span>Players marked as dropped out appear here, and can be reinstated from their row menu.</span></> : <><strong>No players found</strong><span>Try adjusting your search or filters.</span></>}</div> : <div className="eb-players-table-wrap"><table className="eb-players-table"><thead><tr><th className="check"><button onClick={directory.toggleAll} className={directory.visible.every((player) => directory.selected.has(player.id)) ? 'checked' : ''}>{directory.visible.every((player) => directory.selected.has(player.id)) ? <Check size={11} /> : null}</button></th><th><button onClick={() => directory.toggleSort('name')}>Player {directory.sortKey === 'name' && (directory.sortDirection === 'asc' ? <ArrowUp size={10} /> : <ArrowDown size={10} />)}</button></th><th className="team-col">Team</th><th>Position</th><th><button onClick={() => directory.toggleSort('jersey')}>No. {directory.sortKey === 'jersey' && (directory.sortDirection === 'asc' ? <ArrowUp size={10} /> : <ArrowDown size={10} />)}</button></th><th className="profile-col">Profile</th><th>Status</th><th>Actions</th></tr></thead><tbody>{directory.visible.map((player) => <PlayerRow key={player.id} player={player} directory={directory} />)}</tbody></table></div>; }

function PlayerRow({ player, directory }: { player: ReturnType<typeof usePlayersDirectory>['visible'][number]; directory: ReturnType<typeof usePlayersDirectory> }) { const name = getPlayerName(player); const pos = getPositionKey(player.position); const position = PLAYER_POSITIONS[pos] ?? { label: player.position ?? '—', color: '#8a817a' }; const missing = getMissingProfileFields(player); const complete = getProfileCompleteness(player); const selected = directory.selected.has(player.id); const openProfile = (event: MouseEvent<HTMLTableRowElement>) => { if ((event.target as Element).closest('a,button,input,select,label')) return; if (window.getSelection()?.toString()) return; window.location.assign(`/admin/players/${player.id}`); }; return <tr className={`eb-player-row${selected ? ' selected' : ''}`} onClick={openProfile}><td className="check"><button className={selected ? 'checked' : ''} onClick={() => directory.toggleSelection(player.id)}>{selected ? <Check size={11} /> : null}</button></td><td><div className="eb-player-cell"><span className="eb-player-avatar" style={{ background: `${position.color}22`, color: position.color }}>{player.image ? <img src={player.image} alt="" /> : getInitials(name)}</span><div><a className="eb-player-name" href={`/admin/players/${player.id}`}>{name}</a><small>{missing.length ? `Needs ${missing.join(', ')}` : 'Profile complete'}<span className="mobile-team"> · {player.team?.name ?? 'No team'}</span></small></div></div></td><td className="team-col"><div className="eb-player-team"><span style={{ background: `${position.color}22`, color: position.color }}>{getInitials(player.team?.name ?? 'TM')}</span><div><strong>{player.team?.name ?? 'No team'}</strong><small>{player.team?.shortName ?? 'Team'}</small></div></div></td><td><span className="eb-position" style={{ color: position.color }}><b style={{ background: `${position.color}22`, color: position.color }}>{pos || '—'}</b>{position.label.replace(' Guard', '')}</span></td><td><strong className={`eb-jersey ${player.jerseyNumber == null ? 'empty' : ''}`}>{player.jerseyNumber ?? '—'}</strong></td><td className="profile-col"><div className="eb-profile-progress"><span><i style={{ width: `${complete}%`, background: complete === 100 ? '#1f9d55' : position.color }} /></span><b>{complete}%</b></div>{missing.length > 0 && <small>Missing {missing.join(' · ')}</small>}</td><td><button className={`eb-player-status ${player.approved ? 'approved' : 'pending'}`} onClick={() => directory.toggleApproval(player.id, !player.approved)}><i />{player.approved ? 'Approved' : 'Pending'}</button>{player.dropout && <small className="eb-player-dropout" title={`Left the league on ${new Date(player.dropout.droppedOutAt).toLocaleDateString()}`}>Dropped out</small>}</td><td className="actions"><div className="eb-row-actions"><RowMenu label={`Actions for ${name}`} icon={<MoreHorizontal size={16} />} items={[
    { label: 'View profile', href: `/admin/players/${player.id}` },
    { label: 'Edit details', href: `/admin/players/${player.id}/edit` },
    { label: player.approved ? 'Revoke approval' : 'Approve player', onSelect: () => void directory.toggleApproval(player.id, !player.approved), separatorBefore: true },
    player.dropout
      ? { label: 'Reinstate player', onSelect: () => directory.setDropout([player.id], 'REINSTATE') }
      : { label: 'Mark as dropped out…', onSelect: () => directory.setDropout([player.id], 'DROP_OUT') },
    ...(player.dropout ? [] : [{ label: 'Transfer to another team…', onSelect: () => directory.transfer(player.id) }]),
    { label: 'Delete player…', onSelect: () => directory.bulkDelete([player.id]), danger: true, separatorBefore: true },
  ]} /></div></td></tr>; }

function PlayersDialog(directory: ReturnType<typeof usePlayersDirectory>) {
  const { kind, ids } = directory.dialog!;
  const who = directory.describeIds(ids);
  const many = ids.length > 1;
  if (kind === 'TRANSFER')
    return <TransferDialog playerId={ids[0]} playerName={directory.nameOf(ids[0])} onCancel={() => directory.setDialog(null)} onDone={(text) => void directory.finishTransfer(text)} />;
  const common = { busy: directory.busy, onCancel: () => directory.setDialog(null), onConfirm: (reason: string) => void directory.confirmDialog(reason) };
  if (kind === 'DROP_OUT')
    return <ActionDialog {...common} eyebrow="League participation" title={`Mark ${who} as dropped out?`} body={`They come off every roster they are active on, which frees the spot${many ? 's' : ''}, and leave upcoming lineups. Their stats stay on record and you can reinstate them later.`} reasonLabel="Reason (optional, admins only)" reasonPlaceholder="e.g. Relocated, personal reasons" confirmLabel="Mark dropped out" />;
  if (kind === 'REINSTATE')
    return <ActionDialog {...common} eyebrow="League participation" title={`Reinstate ${who}?`} body={`They go back on the roster they most recently left. This fails for anyone who has since joined another roster this season.`} confirmLabel="Reinstate" />;
  return <ActionDialog {...common} danger eyebrow="Delete" title={`Delete ${who}?`} body={`This permanently removes the profile${many ? 's' : ''}, registrations and stats and cannot be undone. If ${many ? 'they have' : 'the player has'} only left the league, cancel and use “Mark as dropped out” instead.`} confirmLabel={`Delete ${many ? `${ids.length} players` : 'player'}`} />;
}

function BulkBar(directory: ReturnType<typeof usePlayersDirectory>) {
  const ids = [...directory.selected];
  const selected = directory.players.filter((player) => directory.selected.has(player.id));
  const dropped = selected.filter((player) => player.dropout).map((player) => player.id);
  const active = selected.filter((player) => !player.dropout).map((player) => player.id);
  const pending = selected.filter((player) => !player.approved).map((player) => player.id);
  return <div className="eb-players-bulk" role="region" aria-label="Bulk actions">
    <strong><span>{ids.length}</span> selected<button className="eb-bulk-clear" onClick={() => directory.setSelected(new Set())}>Clear</button></strong>
    <div className="eb-bulk-actions">
      <button disabled={directory.busy || !pending.length} title={pending.length ? undefined : 'All selected players are already approved'} onClick={() => void directory.bulkApprove(pending)}><CheckCircle2 size={14} /> Approve{pending.length && pending.length !== ids.length ? ` ${pending.length}` : ''}</button>
      <button disabled={directory.busy || !active.length} onClick={() => void directory.setDropout(active, 'DROP_OUT')}><LogOut size={14} /> Mark dropped out{active.length && active.length !== ids.length ? ` ${active.length}` : ''}</button>
      {dropped.length > 0 && <button disabled={directory.busy} onClick={() => void directory.setDropout(dropped, 'REINSTATE')}><RotateCcw size={14} /> Reinstate{dropped.length !== ids.length ? ` ${dropped.length}` : ''}</button>}
      <button disabled={directory.busy} onClick={() => directory.exportCsv(ids)}><Download size={14} /> Export CSV</button>
      <button className="danger" disabled={directory.busy} onClick={() => void directory.bulkDelete(ids)}><Trash2 size={14} /> Delete</button>
    </div>
  </div>;
}

function Kpi({ value, label, color, action, onAction }: { value: number; label: string; color: string; action?: string; onAction?: () => void }) { return <div className="eb-player-kpi"><div><span style={{ background: `${color}22`, color }}><UsersRound size={16} /></span><div><strong>{value}</strong><small>{label}</small></div></div>{action && <button onClick={onAction}>{action}</button>}</div>; }
