-- Add four new MatchEventType values: FOUL_UNSPORTSMANLIKE, FOUL_BENCH_TECHNICAL,
-- FOUL_COACH_TECHNICAL, EJECTION. MySQL/MariaDB ENUMs require re-declaring the
-- full list on ALTER, so every existing value is repeated below.

-- AlterTable
ALTER TABLE `match_events` MODIFY COLUMN `event_type` ENUM(
  'TWO_POINT_MADE',
  'TWO_POINT_MISSED',
  'THREE_POINT_MADE',
  'THREE_POINT_MISSED',
  'FREE_THROW_MADE',
  'FREE_THROW_MISSED',
  'ASSIST',
  'REBOUND_OFFENSIVE',
  'REBOUND_DEFENSIVE',
  'STEAL',
  'BLOCK',
  'TURNOVER',
  'FOUL_PERSONAL',
  'FOUL_TECHNICAL',
  'FOUL_FLAGRANT',
  'FOUL_UNSPORTSMANLIKE',
  'FOUL_BENCH_TECHNICAL',
  'FOUL_COACH_TECHNICAL',
  'EJECTION',
  'SUBSTITUTION_IN',
  'SUBSTITUTION_OUT',
  'TIMEOUT',
  'INJURY',
  'BREAK',
  'PLAY_RESUMED',
  'JUMP_BALL',
  'OTHER'
) NOT NULL;
